# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'floorplandesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FPDWindow(object):
    def setupUi(self, FPDWindow):
        FPDWindow.setObjectName("FPDWindow")
        FPDWindow.resize(1073, 673)
        self.centralwidget = QtWidgets.QWidget(FPDWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.saveFloorplanButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveFloorplanButton.setGeometry(QtCore.QRect(10, 40, 161, 31))
        self.saveFloorplanButton.setObjectName("saveFloorplanButton")
        self.loadFloorplanButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadFloorplanButton.setGeometry(QtCore.QRect(10, 80, 161, 31))
        self.loadFloorplanButton.setObjectName("loadFloorplanButton")
        self.newFloorplanButton = QtWidgets.QPushButton(self.centralwidget)
        self.newFloorplanButton.setGeometry(QtCore.QRect(10, 120, 161, 31))
        self.newFloorplanButton.setObjectName("newFloorplanButton")
        self.floorplanView = QtWidgets.QTabWidget(self.centralwidget)
        self.floorplanView.setGeometry(QtCore.QRect(410, 40, 631, 521))
        self.floorplanView.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.floorplanView.setDocumentMode(True)
        self.floorplanView.setObjectName("floorplanView")
        self.overviewTab = QtWidgets.QWidget()
        self.overviewTab.setObjectName("overviewTab")
        self.r1 = QtWidgets.QFrame(self.overviewTab)
        self.r1.setGeometry(QtCore.QRect(20, 20, 120, 80))
        font = QtGui.QFont()
        font.setKerning(True)
        self.r1.setFont(font)
        self.r1.setFrameShape(QtWidgets.QFrame.Box)
        self.r1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r1.setLineWidth(1)
        self.r1.setObjectName("r1")
        self.floorplanView.addTab(self.overviewTab, "")
        self.room1 = QtWidgets.QWidget()
        self.room1.setObjectName("room1")
        self.r1_full = QtWidgets.QFrame(self.room1)
        self.r1_full.setGeometry(QtCore.QRect(20, 20, 600, 480))
        font = QtGui.QFont()
        font.setKerning(True)
        self.r1_full.setFont(font)
        self.r1_full.setFrameShape(QtWidgets.QFrame.Box)
        self.r1_full.setFrameShadow(QtWidgets.QFrame.Plain)
        self.r1_full.setLineWidth(1)
        self.r1_full.setObjectName("r1_full")
        self.floorplanView.addTab(self.room1, "")
        self.optionsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.optionsBox.setGeometry(QtCore.QRect(10, 160, 361, 461))
        self.optionsBox.setAlignment(QtCore.Qt.AlignCenter)
        self.optionsBox.setObjectName("optionsBox")
        self.addRoomButton = QtWidgets.QPushButton(self.optionsBox)
        self.addRoomButton.setGeometry(QtCore.QRect(150, 30, 75, 31))
        self.addRoomButton.setObjectName("addRoomButton")
        self.textEdit = QtWidgets.QTextEdit(self.optionsBox)
        self.textEdit.setGeometry(QtCore.QRect(23, 30, 111, 31))
        self.textEdit.setObjectName("textEdit")
        FPDWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FPDWindow)
        self.statusbar.setObjectName("statusbar")
        FPDWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FPDWindow)
        self.floorplanView.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FPDWindow)

    def retranslateUi(self, FPDWindow):
        _translate = QtCore.QCoreApplication.translate
        FPDWindow.setWindowTitle(_translate("FPDWindow", "MainWindow"))
        self.saveFloorplanButton.setText(_translate("FPDWindow", "Save Floorplan"))
        self.loadFloorplanButton.setText(_translate("FPDWindow", "Load Floorplan"))
        self.newFloorplanButton.setText(_translate("FPDWindow", "Create New Floorplan"))
        self.floorplanView.setTabText(self.floorplanView.indexOf(self.overviewTab), _translate("FPDWindow", "Overview"))
        self.floorplanView.setTabText(self.floorplanView.indexOf(self.room1), _translate("FPDWindow", "Room 1"))
        self.optionsBox.setTitle(_translate("FPDWindow", "Overview Options"))
        self.addRoomButton.setText(_translate("FPDWindow", "Add Room"))
