# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'floorplandesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FPDWindow(object):
    def setupUi(self, FPDWindow):
        FPDWindow.setObjectName("FPDWindow")
        FPDWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(FPDWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.saveFloorplanButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveFloorplanButton.setGeometry(QtCore.QRect(30, 40, 141, 31))
        self.saveFloorplanButton.setObjectName("saveFloorplanButton")
        self.loadFloorplanButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadFloorplanButton.setGeometry(QtCore.QRect(30, 80, 141, 31))
        self.loadFloorplanButton.setObjectName("loadFloorplanButton")
        self.newFloorplanButton = QtWidgets.QPushButton(self.centralwidget)
        self.newFloorplanButton.setGeometry(QtCore.QRect(30, 120, 141, 31))
        self.newFloorplanButton.setObjectName("newFloorplanButton")
        FPDWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FPDWindow)
        self.statusbar.setObjectName("statusbar")
        FPDWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FPDWindow)
        QtCore.QMetaObject.connectSlotsByName(FPDWindow)

    def retranslateUi(self, FPDWindow):
        _translate = QtCore.QCoreApplication.translate
        FPDWindow.setWindowTitle(_translate("FPDWindow", "MainWindow"))
        self.saveFloorplanButton.setText(_translate("FPDWindow", "Save Floorplan"))
        self.loadFloorplanButton.setText(_translate("FPDWindow", "Load Floorplan"))
        self.newFloorplanButton.setText(_translate("FPDWindow", "Create New Floorplan"))
